# Generated by Django 5.1.5 on 2025-02-05 20:38

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='files/'),
        ),
    ]
