# Generated by Django 5.1.5 on 2025-02-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_folder_parentfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='isTempDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
